#==================================
#= server port
#===================================
server:
  port: 8080
#  error:
#      whitelabel:
#        enabled: false


# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    username: root
    password: Dref@55_A
    url: jdbc:mysql://localhost:3306/dairy?autoReconnect=true&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
      show_sql: true
      format_sql: true
      hibernate:
        ddl-auto: update

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
      cache: false
      mode: LEGACYHTML5

#=================================
# Multipart properties
#=================================
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2kb
      max-file-size: 3MB
      max-request-size: 5MB

