#==================================
#= server port
#===================================
server:
  port: 8080


# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    username: root
    password: Dref@55_A

    url:  jdbc:mysql://localhost:3306/dairyManagementSystem?autoReconnect=true&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
      check-template: true
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html




# ===============================
# = SPRING MAIL
# ===============================
  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: mozdemilly@gmail.com
      password: 20463183
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false