#==================================
#= server port
#===================================

server:
  port: 8080

# ===============================
# = DATA SOURCE
# ===============================

spring:
  datasource:
    username:  root
    password: 2535

    url:  jdbc:mysql://localhost:3306/dairyManagementSystem?autoReconnect=true&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================

  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# ===============================
# = Thymeleaf configurations
# ===============================

  thymeleaf:
      cache: false
      mode: LEGACYHTML5

# ===============================
# = Mail configurations
# ===============================

  mail:
    host: smtp.gmail.com
    port: 465
    username: mozdemilly
    password: 20463183
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: false
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
