#==================================
#= server port
#===================================
server:
  port: 8000


# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    username: root
    password: 07022tolb

    url: jdbc:mysql://localhost:3306/dairyManagementSystem?autoReconnect=true&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
      cache: false
      mode: LEGACYHTML5


