#==================================
#= server port
#===================================
server:
  port: 8080


# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
<<<<<<< HEAD
    username: root
    password: 2535
=======
    username:
    password:
>>>>>>> f6302b47680cd9f34917461f7119f3cbc6e07102

    url: jdbc:mysql://localhost:3306/dairyManagementSystem?autoReconnect=true&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1
<<<<<<< HEAD
=======

>>>>>>> f6302b47680cd9f34917461f7119f3cbc6e07102
# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
      cache: false
      mode: LEGACYHTML5


<<<<<<< HEAD

=======
>>>>>>> f6302b47680cd9f34917461f7119f3cbc6e07102
